name: CI

on:
  push:
    branches: [ main, staging, '**/*' ]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      - name: Install backend deps
        run: pip install -r requirements.txt
      - name: Run backend tests
        run: pytest -q

  frontend-unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend deps
        run: npm ci
      - name: Type check
        run: npm run type-check
      - name: Run unit tests
        run: npm run test:unit
        env:
          VITE_PLANNER_ENABLED: 'true'
          VITE_TIME_EDIT_ENABLED: 'true'
          VITE_SENTRY_DSN: ''

  frontend-e2e:
    needs: frontend-unit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend deps
        run: npm ci
      - name: Install Playwright (Chromium) with deps
        run: npx playwright install --with-deps chromium
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          VITE_PLANNER_ENABLED: 'true'
          VITE_TIME_EDIT_ENABLED: 'true'
          VITE_SENTRY_DSN: ''
          PLAYWRIGHT_BASE_URL: 'http://localhost:5173'

  frontend-e2e-staging-smoke:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend deps
        run: npm ci
      - name: Install Playwright (Chromium) with deps
        run: npx playwright install --with-deps chromium
      - name: Run staging smoke E2E against Vercel
        run: npx playwright test tests/e2e/staging-smoke.spec.ts
        env:
          PLAYWRIGHT_BASE_URL: 'https://trafella.vercel.app'
          PLAYWRIGHT_SKIP_WEB_SERVER: 'true'
          VITE_PLANNER_ENABLED: 'true'
          VITE_TIME_EDIT_ENABLED: 'true'
          VITE_SENTRY_DSN: ''
